---
- hosts: all
  beocme: yes
  tasks: 
    - name: install apache2 and update
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: enable and restart apache2
      service: 
        name: apache2
        enabled: yes
        state: started
